name = "IntegerIB"
uuid = "6503ae40-fab4-4b0f-9ca5-b3ead672bc37"
authors = ["Corentin Nelias <cwokpoubelle@laposte.net>"]
version = "0.1.1"

[deps]
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]

[compat]
julia = "^1.0"
DataFrames = "^1.2.2"
